# Generated by Django 5.2.10 on 2026-01-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion',
        ),
    ]
