# Generated by Django 5.2.10 on 2026-01-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('preparado', 'Preparado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('bodega', models.ForeignKey(help_text='Bodega donde se recogerá el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='bodegas.bodega')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que realiza el pedido (puede ser visitante)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.presentacion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
        ),
    ]
