# Generated by Django 5.2.10 on 2026-01-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(help_text='Correo personal del empleado', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('puesto', models.CharField(help_text='Puesto general del empleado (Cajero, Administrador, Auxiliar, etc.)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='bodegas.bodega')),
                ('user', models.OneToOneField(help_text='Usuario del sistema', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('nivel_acceso', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('turno', models.CharField(max_length=20)),
            ],
        ),
    ]
